Resources:
  RandomRunsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Generate a name based on the stage
      TableName: ${self:custom.stage}-random-runs
      AttributeDefinitions:
        - AttributeName: random_id
          AttributeType: S
      KeySchema:
        - AttributeName: random_id
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}